#!/bin/bash
# vim:ft=bash

if [[ -z $1 ]]; then
  echo "you must enter a directory to sync"
	exit 1
fi


case "$1" in
  fonts)
    stow -vRt ~ "$1"
    fc-cache -fv
    ;;
  *)
    stow -vRt ~ "$1"
    ;;
esac
