# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
windowrule = float on, match:class org\.gnome\.World\.Iotas
windowrule = size 900 700, match:class org\.gnome\.World\.Iotas
windowrule = move 63% 5%, match:class org\.gnome\.World\.Iotas
