#!/usr/bin/env bash

items=$(~/.local/bin/bw list items --session 5bV3kCnJgAG49Dtzlx/3YmnkkpRwjeRpTPmUrBb0/BwzcM3nl2Rv2G+d/UZCJMrNcs1atCMNv0MNP3MPcTI1qA== | jq -r "map({ (.name|tostring): .login.password })|add")
key=$(echo "$items" | jq -r ".|keys[]" | rofi -theme ~/.config/rofi/themes/catppuccin.rasi -dmenu -markup-rows -i -p "Domain" -cycle -sorting-method fzf -sort)
password=$(echo "$items" | jq ".\"$key\"")

if [ "$password" == "null" ]; then
  exit 0
fi

password=${password:1:-1}

echo -n "$password" | xclip -selection clipboard
