#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="50x40"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE

fg=c0caf5
wrong=db4b4b
date=7aa2f7
verify=7aa2f7

betterlockscreen --lock -u $PICTURE --fx dim,pixel,color
